# Use root/example as user/password credentials
version: '3.1'
#sudo docker-compose -f onlydb.yml up
#http://localhost:5001/

services:

    db:
        image: mariadb
        ports:
            - 3366:3306        
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./db:/var/lib/mysql    

    adminer:
        image: adminer
        ports:
            - 5000:8080

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - db:mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
          - '5001:80'
                             
